= LeoCode
Besic Benjamin, Ignjatovic David, Raid Yimne, Spasenovic Bozidar
1.0.0, yyyy-mm-dd: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft

=== Ausgangssituation

Die HTL Leonding ist eine HTL mit ungefähr 1000 Schülern und den Abteilungen Medientechnik, Informatik, Medizintechnik sowie Elektronik.

=== Istzustand

In allen Zweigen spielt das praktische Programmieren eine mehr oder weniger große Rolle, besonders in den Medientechnik bzw. Informatik Zweigen.
Bei den ersten Klassen sind meistens viele Schüler dabei, die noch nie Erfahrung mit Programmieren hatten.

=== Problemstellung

Viele Schüler haben aber durch den Lehrplan nicht genug praktische Übung im Unterricht und kennen sich meistens nicht bei den Hausübungen aus. +
Noch dazu haben die ersten Klassen öfters Probleme mit den IDE's. Meistens haben sie keinen Zugriff oder irgendetwas hat nicht funktioniert.

=== Aufgabenstellung

Zu entwickeln ist ein Platform welche:

* Es ermöglicht Schülern C# Code-Beispiele zu Programmieren

* Schüler auf Ihre Abgaben Feedback bzw. die Lösung bereitstellt

* Dem Lehrpersonal ermöglicht Beispiele inklusive Tests zu erstellen


==== Funktionale Anforderungen
[plantuml,ucd,png]
----
@startuml
left to right direction
:Lehrer:
:Student:

rectangle LeoCode{
Student --> (login)
Lehrer --> (login)

(login) .> (anzeigen von erledigten Aufgaben)
        (login) .> (Aufgaben programmieren)
        (login) .> (Aufgaben sehen)



}

@enduml
----



==== Nichtfunktionale Anforderungen

* Benutzerfreundlichkeit

* Verlässlichkeit

* Effizienz

* Performance

* Wartbarkeit

=== Ziele

* Schüler bekommen eine Vielfalt von Beispielen inklusive Unterrichtsbeispielen bereitgestellt.

* Eine verstärkte Koordination des Unterrichts in den jeweiligen Schulstufen und auch zwischen Parallelklassen.

* Das Übermitteln von Programmiermethoden an die Schüler wird den Lehrer erleichtert.

=== Mengengerüst
Hunderte von Schülern bekommen eine Auswahl von C# Code Beispielen, die sie programmieren können.
Das Programm wird gleichzeitig kompiliert.
Nach der Abgabe bekommen sie ein Feedback von dem jeweiligen Lehrer.

=== Rahmenbedingungen
Noch nicht vorgegeben

=== Systemarchitektur
[plantuml]
----
@startuml

node "<<not defined yet>>\nLeoCodeC#Testing" as n1

node "<<quarkus>>\n LeoBackend" as n2

node "<<nodeJS>>\n LeoGui" as n3

node "<<angular>>\n Browser" as n4

interface TestApi

interface BackendApi

interface GuiApi

package Jenkins{
[ProjectUnderTest]
}

package "local git-repo" as l1{
[ProjectUnderTestRepo]
}

left to right direction
ProjectUnderTest -u-> ProjectUnderTestRepo
n1 --> l1
n1 -r-> TestApi
n2 .-l-> TestApi : use
n2 -r-> BackendApi
n3 .-l-> BackendApi : use
n3 -r-> GuiApi
n4 .-l-> GuiApi : use

@enduml
----
== Projekthandbuch "Organisatorische Rahmenbedingungen"

=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

* link:minutes-of-meeting[Protokollvorlage]
* link:demo.html[Demo]

