= Besprechungsprotokoll
1.0, 2021-01-30
ifndef::imagesdir[:imagesdir: images]
:icons: font
:toc: left

ifdef::backend-html5[]
icon:github-square[link=https://github.com/htl-leonding-project/leo-code]  ‏ ‏ ‎
icon:home[link=https://htl-leonding-project.github.io/leo-code/]  ‏ ‏ ‎
endif::backend-html5[]

.Organisatorisches
|===

|Teilnehmer | Besic, Bahar, Ignjatovic, Raid, Spasenovic
|Ort|Discord
|Datum - Uhrzeit| 30.01.21 17:00
|Dauer| 1 Stunde
|===

== Besprochene Themen

Wir haben besprochen das wir unser Angular Projekt nicht mehr verwenden sollen und dafür ein neues erstellen mit einer besseren Struktur.
Die Struktur wird fur den Theia Editor verwendet. Das Frontend Layout sollte mit einem Login funktionieren und wir sollten noch eine Navbar hinzufügen.
Noch dazu müssen wir das Upload ändern, weil wir ein Zipiupload brauchen.

.Stichwörter
* Neues Angular Project mit entsprechender Struktur https://itnext.io/choosing-a-highly-scalable-folder-structure-in-angular-d987de65ec7 +
* Theia Online Editor einbauen
* Neues Frontend Layout mit Login, Navbar, Zipupload
* Angular üben (Routing etc.)

== Vereinbarungen und Entscheidungen

Wir sollten mit dem Herr Prof. Stuetz sprechen was unsere Nächsten schritte sind und das dann machen.
Uns wurde vorgeschlagen, dass wir das Angular Project Layout benutzen und ein Angular Tutorial machen.
* Besprechung mit Prof. Stütz
* Angular Project Layout benutzen
* Angular Tutorial https://angular.io/tutorial

== Minutes of Meeting

<<minutes-of-meeting.adoc#, Zurück zu den Meetings>>
